spring:
  application:
    name: task-management-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/task-management-service}
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: task-management-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: '*'
      properties:
        spring.json.trusted.packages: com.event_module.model
server:
  port: 8082